### PR TITLE
Adding Countly SDKs

### PR DESCRIPTION
**Pull request by ar2rsawseen**
Hello,
great idea and initiative, gladly joining it :)

### CODE REVIEW

**Comment by rrrene** [comment]
I've added your projects:

https://inch-ci.org/github/Countly/countly-sdk-web
https://inch-ci.org/github/Countly/countly-sdk-nodejs

But you should also be able to do that, as you can sign in via GitHub. If there's any problem with that or if you have any other questions, just ping me! :+1:

**Comment by ar2rsawseen** [comment]
I can't since I signed int with Github, I get:

image

**Comment by rrrene** [comment]
Ouch :disappointed:

Will fix that as soon as I find some time!

**Comment by rrrene** [comment]
Fixed it! Thanks again for reporting! :+1:

**Pull request closed without merging**
